"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-07-10 00:08:42.450010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores da revisão, usados pelo Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escolas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('logotipo_url', sa.String(length=500), nullable=True),
    sa.Column('ano_letivo_ativo', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escolas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escolas_nome'), ['nome'], unique=False)

    op.create_table('quest_mundos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tema', sa.JSON(), nullable=False),
    sa.Column('icone', sa.String(length=16), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quest_mundos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_mundos_slug'), ['slug'], unique=True)

    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('numero_chamada', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('ficha', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alunos_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alunos_nome'), ['nome'], unique=False)

    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=60), nullable=False),
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escola_id', 'namespace', 'chave', name='uq_config')
    )
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuracoes_namespace'), ['namespace'], unique=False)

    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('autor', sa.String(length=200), nullable=True),
    sa.Column('nivel_codigo', sa.String(length=5), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('paginas', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_livros_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_livros_nivel_codigo'), ['nivel_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_livros_titulo'), ['titulo'], unique=False)

    op.create_table('niveis_dificuldade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=True),
    sa.Column('codigos', sa.JSON(), nullable=False),
    sa.Column('pontos_padrao', sa.Float(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('niveis_dificuldade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_niveis_dificuldade_escola_id'), ['escola_id'], unique=False)

    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professores_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_professores_nome'), ['nome'], unique=False)

    op.create_table('quest_jornadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mundo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('ano_escolar', sa.String(length=30), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('bncc', sa.JSON(), nullable=False),
    sa.Column('estrelas_chefao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mundo_id'], ['quest_mundos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quest_jornadas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_jornadas_ano_escolar'), ['ano_escolar'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_jornadas_mundo_id'), ['mundo_id'], unique=False)

    op.create_table('referencias_normalizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('modo', sa.String(length=20), nullable=False),
    sa.Column('valores_manuais', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referencias_normalizacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referencias_normalizacao_escola_id'), ['escola_id'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('senha_visivel', sa.String(length=500), nullable=True),
    sa.Column('cargo', sa.String(length=30), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('conversas_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('provedor', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversas_ia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversas_ia_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversas_ia_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('dificuldade_turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('ano_escolar', sa.String(length=30), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['nivel_id'], ['niveis_dificuldade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escola_id', 'ano_escolar', 'nivel_id', name='uq_dif_serie_nivel')
    )
    with op.batch_alter_table('dificuldade_turma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dificuldade_turma_ano_escolar'), ['ano_escolar'], unique=False)
        batch_op.create_index(batch_op.f('ix_dificuldade_turma_escola_id'), ['escola_id'], unique=False)

    op.create_table('dispositivos_moveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_push', sa.String(length=200), nullable=False),
    sa.Column('plataforma', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispositivos_moveis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispositivos_moveis_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispositivos_moveis_token_push'), ['token_push'], unique=True)
        batch_op.create_index(batch_op.f('ix_dispositivos_moveis_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('importacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('plataforma', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('arquivo_original', sa.String(length=500), nullable=True),
    sa.Column('qtd_alunos', sa.Integer(), nullable=False),
    sa.Column('qtd_erros', sa.Integer(), nullable=False),
    sa.Column('tempo_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('importacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_importacoes_escola_id'), ['escola_id'], unique=False)

    op.create_table('leituras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('tempo_leitura_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'livro_id', name='uq_leitura_unica')
    )
    with op.batch_alter_table('leituras', schema=None) as batch_op:
        batch_op.create_index('ix_leituras_aluno_data', ['aluno_id', 'data'], unique=False)
        batch_op.create_index(batch_op.f('ix_leituras_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leituras_data'), ['data'], unique=False)
        batch_op.create_index('ix_leituras_escola_data', ['escola_id', 'data'], unique=False)
        batch_op.create_index(batch_op.f('ix_leituras_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leituras_livro_id'), ['livro_id'], unique=False)

    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('entidade', sa.String(length=80), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_auditoria_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_auditoria_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_auditoria_escola_id'), ['escola_id'], unique=False)

    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('nota_matific', sa.Float(), nullable=False),
    sa.Column('nota_elefante', sa.Float(), nullable=False),
    sa.Column('nota_geral', sa.Float(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=False),
    sa.Column('calculada_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'ano_letivo', name='uq_nota_aluno_ano')
    )
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_ano_letivo'), ['ano_letivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_escola_id'), ['escola_id'], unique=False)

    op.create_table('quest_credenciais_aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('codigo_login', sa.String(length=20), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id')
    )
    with op.batch_alter_table('quest_credenciais_aluno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_credenciais_aluno_codigo_login'), ['codigo_login'], unique=True)
        batch_op.create_index(batch_op.f('ix_quest_credenciais_aluno_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_credenciais_aluno_qr_token'), ['qr_token'], unique=True)

    op.create_table('quest_missoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('icone', sa.String(length=16), nullable=True),
    sa.Column('descricao_crianca', sa.String(length=300), nullable=True),
    sa.Column('xp_base', sa.Integer(), nullable=False),
    sa.Column('moedas_base', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['quest_jornadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quest_missoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_missoes_jornada_id'), ['jornada_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_missoes_status'), ['status'], unique=False)

    op.create_table('quest_perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=40), nullable=True),
    sa.Column('apelido', sa.String(length=60), nullable=False),
    sa.Column('codigo_amigo', sa.String(length=16), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('moedas', sa.Integer(), nullable=False),
    sa.Column('estrelas_total', sa.Integer(), nullable=False),
    sa.Column('sequencia_dias', sa.Integer(), nullable=False),
    sa.Column('escudo_sequencia', sa.Boolean(), nullable=False),
    sa.Column('ultimo_dia_ativo', sa.Date(), nullable=True),
    sa.Column('avatar', sa.JSON(), nullable=False),
    sa.Column('preferencias', sa.JSON(), nullable=False),
    sa.Column('dificuldade', sa.JSON(), nullable=False),
    sa.Column('social_ativo', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id')
    )
    with op.batch_alter_table('quest_perfis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_perfis_codigo_amigo'), ['codigo_amigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_quest_perfis_escola_id'), ['escola_id'], unique=False)

    op.create_table('responsaveis_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('parentesco', sa.String(length=40), nullable=True),
    sa.Column('autorizado_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['autorizado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'aluno_id', name='uq_responsavel_aluno')
    )
    with op.batch_alter_table('responsaveis_alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responsaveis_alunos_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsaveis_alunos_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responsaveis_alunos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ano_escolar', sa.String(length=30), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('turno', sa.String(length=20), nullable=True),
    sa.Column('capacidade_maxima', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turmas_ano_letivo'), ['ano_letivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turmas_status'), ['status'], unique=False)

    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'ano_letivo', name='uq_matricula_aluno_ano')
    )
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matriculas_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_ano_letivo'), ['ano_letivo'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matriculas_turma_id'), ['turma_id'], unique=False)

    op.create_table('mensagens_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversas_ia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensagens_ia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensagens_ia_conversa_id'), ['conversa_id'], unique=False)

    op.create_table('quest_desafios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('missao_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('mecanica', sa.String(length=30), nullable=False),
    sa.Column('dificuldade', sa.Integer(), nullable=False),
    sa.Column('bncc_codigo', sa.String(length=12), nullable=True),
    sa.Column('corpo', sa.JSON(), nullable=False),
    sa.Column('gabarito', sa.JSON(), nullable=False),
    sa.Column('dica', sa.JSON(), nullable=False),
    sa.Column('explicacao', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['missao_id'], ['quest_missoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quest_desafios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_desafios_bncc_codigo'), ['bncc_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_desafios_missao_id'), ['missao_id'], unique=False)

    op.create_table('quest_habilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('bncc_codigo', sa.String(length=12), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('acertos', sa.Integer(), nullable=False),
    sa.Column('dominio', sa.Float(), nullable=False),
    sa.Column('ultima_atividade_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['quest_perfis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perfil_id', 'bncc_codigo', name='uq_habilidade_perfil_bncc')
    )
    with op.batch_alter_table('quest_habilidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_habilidades_bncc_codigo'), ['bncc_codigo'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_habilidades_perfil_id'), ['perfil_id'], unique=False)

    op.create_table('quest_progresso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('missao_id', sa.Integer(), nullable=False),
    sa.Column('estrelas', sa.Integer(), nullable=False),
    sa.Column('melhor_pct', sa.Float(), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('primeira_conclusao_em', sa.DateTime(), nullable=True),
    sa.Column('ultima_tentativa_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['missao_id'], ['quest_missoes.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['quest_perfis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perfil_id', 'missao_id', name='uq_progresso_perfil_missao')
    )
    with op.batch_alter_table('quest_progresso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quest_progresso_missao_id'), ['missao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_progresso_perfil_id'), ['perfil_id'], unique=False)

    op.create_table('quest_tentativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('missao_id', sa.Integer(), nullable=False),
    sa.Column('missao_versao', sa.Integer(), nullable=False),
    sa.Column('modo', sa.String(length=20), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(), nullable=False),
    sa.Column('finalizada_em', sa.DateTime(), nullable=True),
    sa.Column('total_desafios', sa.Integer(), nullable=False),
    sa.Column('acertos', sa.Integer(), nullable=False),
    sa.Column('tempo_seg', sa.Integer(), nullable=False),
    sa.Column('xp_ganho', sa.Integer(), nullable=False),
    sa.Column('moedas_ganhas', sa.Integer(), nullable=False),
    sa.Column('estrelas', sa.Integer(), nullable=False),
    sa.Column('respostas', sa.JSON(), nullable=False),
    sa.Column('origem', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['missao_id'], ['quest_missoes.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['quest_perfis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quest_tentativas', schema=None) as batch_op:
        batch_op.create_index('ix_quest_tent_escola_fim', ['escola_id', 'finalizada_em'], unique=False)
        batch_op.create_index('ix_quest_tent_perfil_fim', ['perfil_id', 'finalizada_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_tentativas_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_tentativas_missao_id'), ['missao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quest_tentativas_perfil_id'), ['perfil_id'], unique=False)

    op.create_table('snapshots_elefante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('importacao_id', sa.Integer(), nullable=False),
    sa.Column('data_referencia', sa.DateTime(), nullable=False),
    sa.Column('livros_unicos', sa.Integer(), nullable=False),
    sa.Column('tempo_leitura_min', sa.Integer(), nullable=False),
    sa.Column('questoes_tentativas', sa.Integer(), nullable=False),
    sa.Column('questoes_acertos', sa.Integer(), nullable=False),
    sa.Column('livros_por_nivel', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots_elefante', schema=None) as batch_op:
        batch_op.create_index('ix_snap_elefante_escola_aluno_id', ['escola_id', 'aluno_id', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_elefante_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_elefante_data_referencia'), ['data_referencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_elefante_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_elefante_importacao_id'), ['importacao_id'], unique=False)

    op.create_table('snapshots_matific',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('importacao_id', sa.Integer(), nullable=False),
    sa.Column('data_referencia', sa.DateTime(), nullable=False),
    sa.Column('atividades', sa.Integer(), nullable=False),
    sa.Column('estrelas', sa.Integer(), nullable=False),
    sa.Column('pontuacao_media', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshots_matific', schema=None) as batch_op:
        batch_op.create_index('ix_snap_matific_escola_aluno_id', ['escola_id', 'aluno_id', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_matific_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_matific_data_referencia'), ['data_referencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_matific_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_matific_importacao_id'), ['importacao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshots_matific', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_matific_importacao_id'))
        batch_op.drop_index(batch_op.f('ix_snapshots_matific_escola_id'))
        batch_op.drop_index(batch_op.f('ix_snapshots_matific_data_referencia'))
        batch_op.drop_index(batch_op.f('ix_snapshots_matific_aluno_id'))
        batch_op.drop_index('ix_snap_matific_escola_aluno_id')

    op.drop_table('snapshots_matific')
    with op.batch_alter_table('snapshots_elefante', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_elefante_importacao_id'))
        batch_op.drop_index(batch_op.f('ix_snapshots_elefante_escola_id'))
        batch_op.drop_index(batch_op.f('ix_snapshots_elefante_data_referencia'))
        batch_op.drop_index(batch_op.f('ix_snapshots_elefante_aluno_id'))
        batch_op.drop_index('ix_snap_elefante_escola_aluno_id')

    op.drop_table('snapshots_elefante')
    with op.batch_alter_table('quest_tentativas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_tentativas_perfil_id'))
        batch_op.drop_index(batch_op.f('ix_quest_tentativas_missao_id'))
        batch_op.drop_index(batch_op.f('ix_quest_tentativas_escola_id'))
        batch_op.drop_index('ix_quest_tent_perfil_fim')
        batch_op.drop_index('ix_quest_tent_escola_fim')

    op.drop_table('quest_tentativas')
    with op.batch_alter_table('quest_progresso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_progresso_perfil_id'))
        batch_op.drop_index(batch_op.f('ix_quest_progresso_missao_id'))

    op.drop_table('quest_progresso')
    with op.batch_alter_table('quest_habilidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_habilidades_perfil_id'))
        batch_op.drop_index(batch_op.f('ix_quest_habilidades_bncc_codigo'))

    op.drop_table('quest_habilidades')
    with op.batch_alter_table('quest_desafios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_desafios_missao_id'))
        batch_op.drop_index(batch_op.f('ix_quest_desafios_bncc_codigo'))

    op.drop_table('quest_desafios')
    with op.batch_alter_table('mensagens_ia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensagens_ia_conversa_id'))

    op.drop_table('mensagens_ia')
    with op.batch_alter_table('matriculas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matriculas_turma_id'))
        batch_op.drop_index(batch_op.f('ix_matriculas_escola_id'))
        batch_op.drop_index(batch_op.f('ix_matriculas_ano_letivo'))
        batch_op.drop_index(batch_op.f('ix_matriculas_aluno_id'))

    op.drop_table('matriculas')
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turmas_status'))
        batch_op.drop_index(batch_op.f('ix_turmas_escola_id'))
        batch_op.drop_index(batch_op.f('ix_turmas_ano_letivo'))

    op.drop_table('turmas')
    with op.batch_alter_table('responsaveis_alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responsaveis_alunos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_alunos_escola_id'))
        batch_op.drop_index(batch_op.f('ix_responsaveis_alunos_aluno_id'))

    op.drop_table('responsaveis_alunos')
    with op.batch_alter_table('quest_perfis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_perfis_escola_id'))
        batch_op.drop_index(batch_op.f('ix_quest_perfis_codigo_amigo'))

    op.drop_table('quest_perfis')
    with op.batch_alter_table('quest_missoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_missoes_status'))
        batch_op.drop_index(batch_op.f('ix_quest_missoes_jornada_id'))

    op.drop_table('quest_missoes')
    with op.batch_alter_table('quest_credenciais_aluno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_credenciais_aluno_qr_token'))
        batch_op.drop_index(batch_op.f('ix_quest_credenciais_aluno_escola_id'))
        batch_op.drop_index(batch_op.f('ix_quest_credenciais_aluno_codigo_login'))

    op.drop_table('quest_credenciais_aluno')
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_escola_id'))
        batch_op.drop_index(batch_op.f('ix_notas_ano_letivo'))
        batch_op.drop_index(batch_op.f('ix_notas_aluno_id'))

    op.drop_table('notas')
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_escola_id'))
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_created_at'))
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_acao'))

    op.drop_table('logs_auditoria')
    with op.batch_alter_table('leituras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leituras_livro_id'))
        batch_op.drop_index(batch_op.f('ix_leituras_escola_id'))
        batch_op.drop_index('ix_leituras_escola_data')
        batch_op.drop_index(batch_op.f('ix_leituras_data'))
        batch_op.drop_index(batch_op.f('ix_leituras_aluno_id'))
        batch_op.drop_index('ix_leituras_aluno_data')

    op.drop_table('leituras')
    with op.batch_alter_table('importacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_importacoes_escola_id'))

    op.drop_table('importacoes')
    with op.batch_alter_table('dispositivos_moveis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispositivos_moveis_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_dispositivos_moveis_token_push'))
        batch_op.drop_index(batch_op.f('ix_dispositivos_moveis_escola_id'))

    op.drop_table('dispositivos_moveis')
    with op.batch_alter_table('dificuldade_turma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dificuldade_turma_escola_id'))
        batch_op.drop_index(batch_op.f('ix_dificuldade_turma_ano_escolar'))

    op.drop_table('dificuldade_turma')
    with op.batch_alter_table('conversas_ia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversas_ia_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_conversas_ia_escola_id'))

    op.drop_table('conversas_ia')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_escola_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('referencias_normalizacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referencias_normalizacao_escola_id'))

    op.drop_table('referencias_normalizacao')
    with op.batch_alter_table('quest_jornadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_jornadas_mundo_id'))
        batch_op.drop_index(batch_op.f('ix_quest_jornadas_ano_escolar'))

    op.drop_table('quest_jornadas')
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professores_nome'))
        batch_op.drop_index(batch_op.f('ix_professores_escola_id'))

    op.drop_table('professores')
    with op.batch_alter_table('niveis_dificuldade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_niveis_dificuldade_escola_id'))

    op.drop_table('niveis_dificuldade')
    with op.batch_alter_table('livros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_livros_titulo'))
        batch_op.drop_index(batch_op.f('ix_livros_nivel_codigo'))
        batch_op.drop_index(batch_op.f('ix_livros_escola_id'))

    op.drop_table('livros')
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_namespace'))
        batch_op.drop_index(batch_op.f('ix_configuracoes_escola_id'))

    op.drop_table('configuracoes')
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alunos_nome'))
        batch_op.drop_index(batch_op.f('ix_alunos_escola_id'))

    op.drop_table('alunos')
    with op.batch_alter_table('quest_mundos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quest_mundos_slug'))

    op.drop_table('quest_mundos')
    with op.batch_alter_table('escolas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escolas_nome'))

    op.drop_table('escolas')
    # ### end Alembic commands ###
