"""modulo sincronizacao automatica

Revision ID: 0007
Revises: 0006
Create Date: 2026-07-11 11:39:33.369192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores da revisão, usados pelo Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plataforma_credenciais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(length=30), nullable=False),
    sa.Column('segredo_cifrado', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validada_em', sa.DateTime(), nullable=True),
    sa.Column('ultimo_erro', sa.String(length=300), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escola_id', 'plataforma', name='uq_credencial_escola_plat')
    )
    with op.batch_alter_table('plataforma_credenciais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plataforma_credenciais_escola_id'), ['escola_id'], unique=False)

    op.create_table('sincronizacao_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('cadencia', sa.String(length=20), nullable=False),
    sa.Column('hora_local', sa.String(length=5), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('proxima_execucao', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escola_id', 'plataforma', name='uq_syncconfig_escola_plat')
    )
    with op.batch_alter_table('sincronizacao_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sincronizacao_config_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sincronizacao_config_proxima_execucao'), ['proxima_execucao'], unique=False)

    op.create_table('sincronizacao_execucoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(length=30), nullable=False),
    sa.Column('origem', sa.String(length=12), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('disponivel_em', sa.DateTime(), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(), nullable=True),
    sa.Column('finalizada_em', sa.DateTime(), nullable=True),
    sa.Column('duracao_ms', sa.Integer(), nullable=False),
    sa.Column('qtd_alunos', sa.Integer(), nullable=False),
    sa.Column('qtd_turmas', sa.Integer(), nullable=False),
    sa.Column('qtd_alteracoes', sa.Integer(), nullable=False),
    sa.Column('qtd_arquivos', sa.Integer(), nullable=False),
    sa.Column('qtd_erros', sa.Integer(), nullable=False),
    sa.Column('parser_versao', sa.String(length=20), nullable=True),
    sa.Column('conector_versao', sa.String(length=20), nullable=True),
    sa.Column('importacao_id', sa.Integer(), nullable=True),
    sa.Column('tentativa', sa.Integer(), nullable=False),
    sa.Column('erro_resumo', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sincronizacao_execucoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sincronizacao_execucoes_disponivel_em'), ['disponivel_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_sincronizacao_execucoes_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sincronizacao_execucoes_status'), ['status'], unique=False)
        batch_op.create_index('ix_sync_exec_escola_inicio', ['escola_id', 'iniciada_em'], unique=False)

    op.create_table('sincronizacao_alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(length=30), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('severidade', sa.String(length=8), nullable=False),
    sa.Column('mensagem', sa.String(length=500), nullable=False),
    sa.Column('resolvido', sa.Boolean(), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(), nullable=True),
    sa.Column('execucao_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execucao_id'], ['sincronizacao_execucoes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sincronizacao_alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sincronizacao_alertas_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sincronizacao_alertas_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sincronizacao_alertas_resolvido'), ['resolvido'], unique=False)
        batch_op.create_index(batch_op.f('ix_sincronizacao_alertas_tipo'), ['tipo'], unique=False)

    op.create_table('sincronizacao_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execucao_id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.String(length=20), nullable=False),
    sa.Column('nivel', sa.String(length=8), nullable=False),
    sa.Column('mensagem', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execucao_id'], ['sincronizacao_execucoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sincronizacao_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sincronizacao_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sincronizacao_logs_escola_id'), ['escola_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sincronizacao_logs_etapa'), ['etapa'], unique=False)
        batch_op.create_index(batch_op.f('ix_sincronizacao_logs_execucao_id'), ['execucao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sincronizacao_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sincronizacao_logs_execucao_id'))
        batch_op.drop_index(batch_op.f('ix_sincronizacao_logs_etapa'))
        batch_op.drop_index(batch_op.f('ix_sincronizacao_logs_escola_id'))
        batch_op.drop_index(batch_op.f('ix_sincronizacao_logs_created_at'))

    op.drop_table('sincronizacao_logs')
    with op.batch_alter_table('sincronizacao_alertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sincronizacao_alertas_tipo'))
        batch_op.drop_index(batch_op.f('ix_sincronizacao_alertas_resolvido'))
        batch_op.drop_index(batch_op.f('ix_sincronizacao_alertas_escola_id'))
        batch_op.drop_index(batch_op.f('ix_sincronizacao_alertas_created_at'))

    op.drop_table('sincronizacao_alertas')
    with op.batch_alter_table('sincronizacao_execucoes', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_exec_escola_inicio')
        batch_op.drop_index(batch_op.f('ix_sincronizacao_execucoes_status'))
        batch_op.drop_index(batch_op.f('ix_sincronizacao_execucoes_escola_id'))
        batch_op.drop_index(batch_op.f('ix_sincronizacao_execucoes_disponivel_em'))

    op.drop_table('sincronizacao_execucoes')
    with op.batch_alter_table('sincronizacao_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sincronizacao_config_proxima_execucao'))
        batch_op.drop_index(batch_op.f('ix_sincronizacao_config_escola_id'))

    op.drop_table('sincronizacao_config')
    with op.batch_alter_table('plataforma_credenciais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plataforma_credenciais_escola_id'))

    op.drop_table('plataforma_credenciais')
    # ### end Alembic commands ###
