"""unicidade de execucao ativa por escola-plataforma

Revision ID: 0008
Revises: 0007
Create Date: 2026-07-11 12:46:02.658667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores da revisão, usados pelo Alembic.
revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sincronizacao_execucoes', schema=None) as batch_op:
        batch_op.create_index('uq_sync_exec_ativa', ['escola_id', 'plataforma'], unique=True, postgresql_where=sa.text("status IN ('fila', 'executando')"), sqlite_where=sa.text("status IN ('fila', 'executando')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sincronizacao_execucoes', schema=None) as batch_op:
        batch_op.drop_index('uq_sync_exec_ativa', postgresql_where=sa.text("status IN ('fila', 'executando')"), sqlite_where=sa.text("status IN ('fila', 'executando')"))

    # ### end Alembic commands ###
