from app.schemas.comum import (
    AcaoAlunos,
    AlunoCreate,
    AlunoGestaoOut,
    AlunoOut,
    AlunoPerfilOut,
    AlunoUpdate,
    DashboardOut,
    ExclusaoPermanenteAlunos,
    FusaoAlunos,
    DificuldadeSerieOut,
    DificuldadeUpdate,
    EscolaCreate,
    EscolaOut,
    EscolaUpdate,
    LoginOut,
    NivelOut,
    PesosOut,
    PesosUpdate,
    ProfessorCreate,
    ProfessorOut,
    RankingItemOut,
    ReferenciasOut,
    ReferenciasUpdate,
    TurmaCreate,
    TurmaOut,
    TurmaUpdate,
    UsuarioOut,
)
from app.schemas.importacao import (
    AnaliseOut,
    CorrespondenciaOut,
    ImportacaoConfirm,
    ImportacaoOut,
    ImportacaoResultadoOut,
    LinhaAnaliseOut,
    LinhaConfirmacao,
    MatriculaTurmaOut,
    MatriculasAnaliseOut,
    MatriculasResultadoOut,
)
from app.schemas.plataformas import (
    ElefanteAlunoOut,
    ElefanteEdicao,
    LivroCreate,
    LivroOut,
    LivroUpdate,
    MatificAlunoOut,
    MatificEdicao,
    NiveisLeituraEdicao,
)

__all__ = [n for n in dir() if not n.startswith("_")]
